package com.aura.defense.ui.components

import android.widget.Toast
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.aura.defense.security.GeoFenceMonitor
import com.aura.defense.security.GeoFenceResult
import com.aura.defense.security.SmsPhishingDetector
import com.aura.defense.security.SmsPhishingResult
import com.aura.defense.security.TotpAuthenticator
import com.aura.defense.security.TotpEntry
import com.aura.defense.ui.AuraAmber
import com.aura.defense.ui.AuraCyan
import com.aura.defense.ui.AuraGreen
import com.aura.defense.ui.AuraMuted
import com.aura.defense.ui.AuraRed
import com.aura.defense.ui.AuraSurfaceRaised
import kotlinx.coroutines.delay

@Composable
fun AuraPhase4Dialog(onDismiss: () -> Unit) {
        var smsInput by remember { mutableStateOf("") }
            var smsResult by remember { mutableStateOf<SmsPhishingResult?>(null) }
                var totpLabel by remember { mutableStateOf("") }
                    var totpIssuer by remember { mutableStateOf("") }
                        var totpSecret by remember { mutableStateOf("") }
                            var totpEntries by remember { mutableStateOf<List<TotpEntry>>(emptyList()) }
                                var totpCodes by remember { mutableStateOf<Map<String, String>>(emptyMap()) }
                                    var totpRemaining by remember { mutableIntStateOf(30) }
                                        var geoResult by remember { mutableStateOf<GeoFenceResult?>(null) }
                                            var zoneName by remember { mutableStateOf("") }
                                                var tunnelMode by remember { mutableStateOf("") }
                                                    var connCount by remember { mutableStateOf(0L) }
                                                        var blockedCount by remember { mutableStateOf(0L) }
                                                            val ctx = LocalContext.current
                                                                val totpAuth = remember { TotpAuthenticator(ctx) }
                                                                    val geoMonitor = remember { GeoFenceMonitor(ctx) }
                                                                        val tunnelEngine = remember { com.aura.defense.vpn.AuraFullTunnelEngine(ctx) }

                                                                            LaunchedEffect(Unit) {
                                                                                        totpEntries = totpAuth.getEntries()
                                                                                                tunnelMode = tunnelEngine.getTunnelMode()
                                                                                                        connCount = tunnelEngine.getTotalConnections()
                                                                                                                blockedCount = tunnelEngine.getBlockedCount()
                                                                            }
                                                                                LaunchedEffect(totpRemaining) {
                                                                                            delay(1000)
                                                                                                    totpRemaining = totpAuth.getRemainingSeconds()
                                                                                                            if (totpEntries.isNotEmpty()) {
                                                                                                                            val codes = mutableMapOf<String, String>()
                                                                                                                                        totpEntries.forEach { entry ->
                                                                                                                                                        codes[entry.id] = totpAuth.generateCodeForEntry(entry)
                                                                                                                                                                    }
                                                                                                                                                                                totpCodes = codes
                                                                                                            }
                                                                                }

                                                                                    AuraHudDialog(
                                                                                                onDismissRequest = onDismiss,
                                                                                                        title = { Text("Funciones Avanzadas") },
                                                                                                                text = {
                                                                                                                                Column(
                                                                                                                                                    modifier = Modifier.verticalScroll(rememberScrollState()),
                                                                                                                                                                    verticalArrangement = Arrangement.spacedBy(8.dp)
                                                                                                                                ) {
                                                                                                                                                    // --- SMS Phishing Detector ---
                                                                                                                                                                    AdvToolDescription("Detector de SMS de phishing")
                                                                                                                                                                                    OutlinedTextField(
                                                                                                                                                                                                            value = smsInput,
                                                                                                                                                                                                                                onValueChange = { smsInput = it },
                                                                                                                                                                                                                                                    label = { Text("Pega el SMS aqui") },
                                                                                                                                                                                                                                                                        modifier = Modifier.fillMaxWidth()
                                                                                                                                                                                    )
                                                                                                                                                                                                    TextButton(
                                                                                                                                                                                                                            onClick = {
                                                                                                                                                                                                                                                        if (smsInput.isNotBlank()) {
                                                                                                                                                                                                                                                                                        smsResult = SmsPhishingDetector().analyze(smsInput)
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                enabled = smsInput.isNotBlank()
                                                                                                                                                                                                    ) { Text("Analizar SMS") }
                                                                                                                                                                                                                    smsResult?.let { r ->
                                                                                                                                                                                                                                        val riskColor = when (r.riskLevel) {
                                                                                                                                                                                                                                                                    "CRITICO" -> AuraRed
                                                                                                                                                                                                                                                                                            "ALTO" -> AuraAmber
                                                                                                                                                                                                                                                                                                                    "MEDIO" -> AuraCyan
                                                                                                                                                                                                                                                                                                                                            else -> AuraGreen
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                            Text("Riesgo: ${r.riskLevel} | Phishing: ${if (r.isPhishing) "SI" else "No"}", color = riskColor, fontSize = 12.sp)
                                                                                                                                                                                                                                                                                r.indicators.forEach { Text("  $it", color = AuraAmber, fontSize = 11.sp) }
                                                                                                                                                                                                                                                                                                    Text(r.explanation, color = AuraMuted, fontSize = 11.sp)
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                    // --- TOTP Authenticator ---
                                                                                                                                                                                                                                                    AdvToolDescription("Autenticador TOTP (2FA)")
                                                                                                                                                                                                                                                                    OutlinedTextField(
                                                                                                                                                                                                                                                                                            value = totpLabel,
                                                                                                                                                                                                                                                                                                                onValueChange = { totpLabel = it },
                                                                                                                                                                                                                                                                                                                                    label = { Text("Nombre") },
                                                                                                                                                                                                                                                                                                                                                        singleLine = true,
                                                                                                                                                                                                                                                                                                                                                                            modifier = Modifier.fillMaxWidth()
                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                    OutlinedTextField(
                                                                                                                                                                                                                                                                                                            value = totpIssuer,
                                                                                                                                                                                                                                                                                                                                onValueChange = { totpIssuer = it },
                                                                                                                                                                                                                                                                                                                                                    label = { Text("Servicio") },
                                                                                                                                                                                                                                                                                                                                                                        singleLine = true,
                                                                                                                                                                                                                                                                                                                                                                                            modifier = Modifier.fillMaxWidth()
                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                    OutlinedTextField(
                                                                                                                                                                                                                                                                                                                            value = totpSecret,
                                                                                                                                                                                                                                                                                                                                                onValueChange = { totpSecret = it },
                                                                                                                                                                                                                                                                                                                                                                    label = { Text("Clave secreta Base32") },
                                                                                                                                                                                                                                                                                                                                                                                        singleLine = true,
                                                                                                                                                                                                                                                                                                                                                                                                            modifier = Modifier.fillMaxWidth()
                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                    TextButton(
                                                                                                                                                                                                                                                                                                                                            onClick = {
                                                                                                                                                                                                                                                                                                                                                                        if (totpLabel.isNotBlank() && totpSecret.isNotBlank()) {
                                                                                                                                                                                                                                                                                                                                                                                                        totpAuth.saveEntry(totpLabel, totpIssuer.ifBlank { "Aura" }, totpSecret)
                                                                                                                                                                                                                                                                                                                                                                                                                                    totpEntries = totpAuth.getEntries()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                totpLabel = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totpIssuer = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        totpSecret = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Toast.makeText(ctx, "Servicio TOTP guardado", Toast.LENGTH_SHORT).show()
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                enabled = totpLabel.isNotBlank() && totpSecret.isNotBlank()
                                                                                                                                                                                                                                                                                                                    ) { Text("Guardar servicio") }

                                                                                                                                                                                                                                                                                                                                    if (totpEntries.isNotEmpty()) {
                                                                                                                                                                                                                                                                                                                                                            Text("Tiempo restante: ${totpRemaining}s", color = AuraMuted, fontSize = 11.sp)
                                                                                                                                                                                                                                                                                                                                                                                totpEntries.forEach { entry ->
                                                                                                                                                                                                                                                                                                                                                                                                        val code = totpCodes[entry.id] ?: "------"
                                                                                                                                                                                                                                                                                                                                                                                                                                Row(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                modifier = Modifier.fillMaxWidth().padding(vertical = 2.dp),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            horizontalArrangement = Arrangement.SpaceBetween
                                                                                                                                                                                                                                                                                                                                                                                                                                ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                Column(modifier = Modifier.weight(1f)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Text("${entry.issuer} - ${entry.label}", color = AuraCyan, fontSize = 12.sp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Text(code, color = AuraGreen, fontSize = 16.sp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TextButton(onClick = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totpAuth.deleteEntry(entry.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totpEntries = totpAuth.getEntries()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }) { Text("X", color = AuraRed, fontSize = 11.sp) }
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                    // --- Geofencing ---
                                                                                                                                                                                                                                                                                                                                                                    AdvToolButton("Verificar geocerca") {
                                                                                                                                                                                                                                                                                                                                                                                            geoResult = geoMonitor.checkGeofence()
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    OutlinedTextField(
                                                                                                                                                                                                                                                                                                                                                                                                            value = zoneName,
                                                                                                                                                                                                                                                                                                                                                                                                                                onValueChange = { zoneName = it },
                                                                                                                                                                                                                                                                                                                                                                                                                                                    label = { Text("Nombre de zona") },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        singleLine = true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            modifier = Modifier.fillMaxWidth()
                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                    TextButton(
                                                                                                                                                                                                                                                                                                                                                                                                                            onClick = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (zoneName.isNotBlank() && geoResult != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        geoMonitor.saveSafeZone(zoneName, geoResult!!.currentLatitude, geoResult!!.currentLongitude, 200)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    geoResult = geoMonitor.checkGeofence()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                zoneName = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Toast.makeText(ctx, "Zona segura guardada", Toast.LENGTH_SHORT).show()
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                enabled = zoneName.isNotBlank() && geoResult != null
                                                                                                                                                                                                                                                                                                                                                                                                    ) { Text("Guardar ubicacion actual como zona segura") }
                                                                                                                                                                                                                                                                                                                                                                                                                    geoResult?.let { r ->
                                                                                                                                                                                                                                                                                                                                                                                                                                        Text("Ubicacion: ${r.currentLatitude}, ${r.currentLongitude}", color = AuraMuted, fontSize = 11.sp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Text("Dentro de zona segura: ${if (r.insideAny) "SI" else "NO"}", color = if (r.insideAny) AuraGreen else AuraRed, fontSize = 12.sp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (r.nearestZone != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Text("Zona mas cercana: ${r.nearestZone} (${r.distanceToNearest}m)", color = AuraMuted, fontSize = 11.sp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    r.warnings.forEach { Text("  $it", color = AuraAmber, fontSize = 11.sp) }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        r.safeZones.forEach { zone ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Text("  ${zone.name}: ${zone.latitude}, ${zone.longitude} (r=${zone.radiusMeters}m)", color = AuraMuted, fontSize = 10.sp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                    // --- Full Tunnel VPN ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                    AdvToolDescription("Tunel VPN completo")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Text("Modo actual: ${if (tunnelMode == "full_tunnel") "Tunel completo" else "Solo DNS"}", color = AuraCyan, fontSize = 12.sp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Text("Conexiones totales: $connCount | Bloqueadas: $blockedCount", color = AuraMuted, fontSize = 11.sp)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    TextButton(onClick = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            val newMode = if (tunnelMode == "full_tunnel") "dns_only" else "full_tunnel"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tunnelEngine.setTunnelMode(newMode)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tunnelMode = newMode
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Text(if (tunnelMode == "full_tunnel") "Cambiar a Solo DNS" else "Cambiar a Tunel Completo")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Spacer(modifier = Modifier.height(8.dp))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Text("Todas las funciones se ejecutan localmente en el dispositivo.", color = AuraMuted, fontSize = 10.sp)
                                                                                                                                }
                                                                                                                },
                                                                                                                        confirmButton = { TextButton(onClick = onDismiss) { Text("Cerrar") } }
                                                                                    )
}

@Composable
private fun AdvToolButton(label: String, onClick: () -> Unit) {
        Surface(
                    modifier = Modifier.fillMaxWidth().padding(vertical = 2.dp).clickable(onClick = onClick),
                            color = AuraSurfaceRaised,
                                    shape = RoundedCornerShape(10.dp),
                                            border = BorderStroke(0.5.dp, AuraCyan.copy(alpha = 0.2f))
        ) {
                    Text(
                                    label,
                                                modifier = Modifier.padding(vertical = 12.dp, horizontal = 16.dp),
                                                            color = AuraCyan,
                                                                        fontSize = 13.sp
                    )
        }
}

@Composable
private fun AdvToolDescription(text: String) {
        Text(text, color = AuraMuted, fontSize = 11.sp, modifier = Modifier.padding(top = 6.dp))
}
